matrix:
  include:
    - os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    docker run --rm \
      -e GH_TOKEN=$GH_TOKEN \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine \
      /bin/bash -c "yarn global add npm && npm install && npx bower install --allow-root && npm run publish"
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
    - "/^v\\d+\\.\\d+\\.\\d+$/"